# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('insert', models.DateTimeField()),
                ('update', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uprn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprn', models.CharField(max_length=100, unique=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr.Title')),
            ],
        ),
        migrations.AddField(
            model_name='polygon',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr.Title'),
        ),
    ]
