# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='lr.Title'),
        ),
    ]
