# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrpoly',
            name='insert',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lrpoly',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
