# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def check_func(apps, schema_editor):
    input('WARNING This will delete all rows of your Land Registry tables. '
          'Press Return to continue')


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0002_auto_20170509_1028'),
    ]

    operations = [
        migrations.RunPython(check_func),
        migrations.RunSQL(
            'DELETE FROM lr_uprn;'),
        migrations.RunSQL(
            'DELETE FROM lr_lrpoly;'),
    ]
