# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0003_auto_20170512_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrpoly',
            name='lrid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='uprn',
            name='lrpoly',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lr.LRPoly'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lrpoly',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uprn',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
